### PR TITLE
Create dummy `want-to-help` and `need-help` endpoints

### LINKED ISSUE #6: Create dummy endpoints for two forms `I want to help` and `I need help`
Purpose of this issue is to create endpoints for the two forms that would return dummy response.

### PR DESCRIPTION
**Pull request by filipjurcak**
Closes #6 

As stated in the title, this PR introduces two dummy endpoints that frontend can start using
Also enables CORS from all domains and routes, which will be handled/restricted in future PR

### CODE REVIEW

**Review by matusf — APPROVED** [review]
lgtm

**Comment by Saamoot** [comment]
Hello,
sorry for late reaction/reacting after merging.

Why was in creation of dummy endpoints [removed prefix of api version (v1) from url](https://github.com/uk-kona/univerzita-kona-api/pull/15/files#diff-1f9f743421417fb2794c88447083a031R17) ?

**Comment by filipjurcak** [comment]
Why should we keep it? Is it a convention? If yes, I would like to know why

**Comment by Saamoot** [comment]
> Why should we keep it? 

To have easy option to create new version of api (namespace).

> Is it a convention?

If yes i don't know about it, version is something that may be usefull in the future.


Not everything needs to be convetion to implement something.

But idea if convetion for something like that exist is good, so it would be good idea
to check if there is such thing and if yes use it.

**Comment by filipjurcak** [comment]
Okay, I haven't thought about versioning API endpoints, which seems like a good point, so I'll add it back it a next PR

**Pull request merged**
